# Generated by Django 3.1 on 2020-08-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMPLOYER',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='non', max_length=20)),
                ('phone', models.CharField(default='non', max_length=11)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='non', max_length=10)),
                ('lastName', models.CharField(default='non', max_length=10)),
                ('phone', models.CharField(default='non', max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('employerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarti.employer')),
            ],
        ),
    ]
